version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Replace with your desired Python version
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
  
      
  pre_build:
    commands:
      - echo "Running pre-build commands"
      - python manage.py collectstatic --noinput  # Collect static files
      - python manage.py makemigrations  # Prepare migrations

  build:
    commands:
      - echo "Running build commands"
      - python manage.py migrate  # Apply database migrations
      - python manage.py test  # Run tests to ensure build quality

  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'  # Include all files in the build artifact
  discard-paths: no  # Keep the original folder structure
