version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install Django
      - pip install --upgrade pip
      - pip install pylint
  pre_build:
    commands:
      - echo "Building the project..."
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py || true
      - pylint $CODEBUILD_SRC_DIR/Story_Forge/*.py || true
      - pylint --disable=R0903,E1101 $CODEBUILD_SRC_DIR/Story_Forge/*.py || true
      - echo "Installing required tools..."
      - pip install --upgrade pip
      - pip install sonar-scanner-cli  # Install SonarScanner
  pre_build:
    commands:
      - echo "Installing dependencies..."
  
  build:
    commands:
      - echo "Running Django tests..."
      - python manage.py test  # Run your Django tests
      - echo "Starting SonarCloud analysis..."
      - sonar-scanner \
        -Dsonar.projectKey="prathameshs1999" \
        -Dsonar.organization="prathameshs1999" \
        -Dsonar.host.url="https://sonarcloud.io" \
        -Dsonar.login="$SONAR_TOKEN" \
        -Dsonar.python.version=3.8  # Specify Python version used
artifacts:
  files:
    - '**/*'
