version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint
  pre_build:
    commands:
      - echo "Building the project..."
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py || true
      - pylint $CODEBUILD_SRC_DIR/expense/*.py || true
      - pylint --disable=R0903,E1101 $CODEBUILD_SRC_DIR/expense/*.py || true
artifacts:
  files:
    - '**/*'
has context menu
